# Generated by Django 4.2.14 on 2024-07-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoria',
        ),
    ]
