# Generated by Django 4.2.14 on 2024-07-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
